# Generated by Django 5.0.4 on 2024-05-08 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_user_followers_remove_user_following_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userfollowing',
            unique_together=set(),
        ),
    ]
